eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: service-hi


#在配置文件中注明自己的服务注册中心的地址
#必须注明spring.application.name，在以后的服务与服务之间的调用一般根据这个name